# Makefile.in generated by automake 1.15 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2014 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# -*- Makefile -*-



am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/openjazz
pkgincludedir = $(includedir)/openjazz
pkglibdir = $(libdir)/openjazz
pkglibexecdir = $(libexecdir)/openjazz
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = openjazz$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(pkgdatadir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_openjazz_OBJECTS = src/game/clientgame.$(OBJEXT) \
	src/game/game.$(OBJEXT) src/game/gamemode.$(OBJEXT) \
	src/game/localgame.$(OBJEXT) src/game/servergame.$(OBJEXT) \
	src/io/gfx/anim.$(OBJEXT) src/io/gfx/font.$(OBJEXT) \
	src/io/gfx/paletteeffects.$(OBJEXT) \
	src/io/gfx/sprite.$(OBJEXT) src/io/gfx/video.$(OBJEXT) \
	src/io/gfx/scale2x/getopt.$(OBJEXT) \
	src/io/gfx/scale2x/pixel.$(OBJEXT) \
	src/io/gfx/scale2x/scale2x.$(OBJEXT) \
	src/io/gfx/scale2x/scale3x.$(OBJEXT) \
	src/io/gfx/scale2x/scalebit.$(OBJEXT) \
	src/io/gfx/scale2x/simple2x.$(OBJEXT) \
	src/io/controls.$(OBJEXT) src/io/file.$(OBJEXT) \
	src/io/network.$(OBJEXT) src/io/sound.$(OBJEXT) \
	src/jj1bonuslevel/jj1bonuslevelplayer/jj1bonuslevelplayer.$(OBJEXT) \
	src/jj1bonuslevel/jj1bonuslevel.$(OBJEXT) \
	src/jj1level/jj1event/jj1bridge.$(OBJEXT) \
	src/jj1level/jj1event/jj1event.$(OBJEXT) \
	src/jj1level/jj1event/jj1guardians.$(OBJEXT) \
	src/jj1level/jj1event/jj1standardevent.$(OBJEXT) \
	src/jj1level/jj1levelplayer/jj1bird.$(OBJEXT) \
	src/jj1level/jj1levelplayer/jj1levelplayer.$(OBJEXT) \
	src/jj1level/jj1levelplayer/jj1levelplayerframe.$(OBJEXT) \
	src/jj1level/jj1bullet.$(OBJEXT) \
	src/jj1level/jj1demolevel.$(OBJEXT) \
	src/jj1level/jj1level.$(OBJEXT) \
	src/jj1level/jj1levelframe.$(OBJEXT) \
	src/jj1level/jj1levelload.$(OBJEXT) \
	src/jj1planet/jj1planet.$(OBJEXT) \
	src/jj1scene/jj1scene.$(OBJEXT) \
	src/jj1scene/jj1sceneload.$(OBJEXT) \
	src/jj2level/jj2event/jj2event.$(OBJEXT) \
	src/jj2level/jj2event/jj2eventframe.$(OBJEXT) \
	src/jj2level/jj2levelplayer/jj2levelplayer.$(OBJEXT) \
	src/jj2level/jj2levelplayer/jj2levelplayerframe.$(OBJEXT) \
	src/jj2level/jj2layer.$(OBJEXT) \
	src/jj2level/jj2level.$(OBJEXT) \
	src/jj2level/jj2levelframe.$(OBJEXT) \
	src/jj2level/jj2levelload.$(OBJEXT) src/level/level.$(OBJEXT) \
	src/level/movable.$(OBJEXT) src/level/levelplayer.$(OBJEXT) \
	src/menu/gamemenu.$(OBJEXT) src/menu/mainmenu.$(OBJEXT) \
	src/menu/menu.$(OBJEXT) src/menu/plasma.$(OBJEXT) \
	src/menu/setupmenu.$(OBJEXT) src/player/player.$(OBJEXT) \
	src/main.$(OBJEXT) src/setup.$(OBJEXT) src/util.$(OBJEXT)
openjazz_OBJECTS = $(am_openjazz_OBJECTS)
am__DEPENDENCIES_1 =
openjazz_DEPENDENCIES = $(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(openjazz_SOURCES)
DIST_SOURCES = $(openjazz_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
DATA = $(pkgdata_DATA)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in depcomp install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
GZIP_ENV = --best
DIST_ARCHIVES = $(distdir).tar.xz
DIST_TARGETS = dist-xz
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/marc/git/openjazz/missing aclocal-1.15
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /home/marc/git/openjazz/missing autoconf
AUTOHEADER = ${SHELL} /home/marc/git/openjazz/missing autoheader
AUTOMAKE = ${SHELL} /home/marc/git/openjazz/missing automake-1.15
AWK = gawk
CPPFLAGS = 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"openjazz\" -DPACKAGE_TARNAME=\"openjazz\" -DPACKAGE_VERSION=\"0\" -DPACKAGE_STRING=\"openjazz\ 0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"openjazz\" -DVERSION=\"0\"
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EXEEXT = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/marc/git/openjazz/missing makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = openjazz
PACKAGE_BUGREPORT = 
PACKAGE_NAME = openjazz
PACKAGE_STRING = openjazz 0
PACKAGE_TARNAME = openjazz
PACKAGE_URL = 
PACKAGE_VERSION = 0
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 0
abs_builddir = /home/marc/git/openjazz
abs_srcdir = /home/marc/git/openjazz
abs_top_builddir = /home/marc/git/openjazz
abs_top_srcdir = /home/marc/git/openjazz
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = tar --format=posix -chf - "$$tardir"
am__untar = tar -xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/marc/git/openjazz/install-sh
libSDL_CFLAGS = -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/include/SDL 
libSDL_LIBS = -lSDL 
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
libmodplug_CFLAGS = 
libmodplug_LIBS = -lmodplug 
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AM_CPPFLAGS = -DUSE_MODPLUG -DUSE_SOCKETS -DSCALE -I${top_srcdir}/src \
              ${libSDL_CFLAGS} ${libmodplug_CFLAGS}

AM_CFLAGS = -Wall
AM_CXXFLAGS = -Wall
pkgdata_DATA = openjazz.000
openjazz_SOURCES = \
	src/game/clientgame.cpp src/game/game.cpp src/game/gamemode.cpp \
	src/game/localgame.cpp src/game/servergame.cpp \
	src/io/gfx/anim.cpp src/io/gfx/font.cpp src/io/gfx/paletteeffects.cpp \
	src/io/gfx/sprite.cpp src/io/gfx/video.cpp \
	src/io/gfx/scale2x/getopt.cpp src/io/gfx/scale2x/pixel.cpp \
	src/io/gfx/scale2x/scale2x.cpp src/io/gfx/scale2x/scale3x.cpp \
	src/io/gfx/scale2x/scalebit.cpp src/io/gfx/scale2x/simple2x.cpp \
	src/io/controls.cpp src/io/file.cpp src/io/network.cpp src/io/sound.cpp \
	src/jj1bonuslevel/jj1bonuslevelplayer/jj1bonuslevelplayer.cpp \
	src/jj1bonuslevel/jj1bonuslevel.cpp \
	src/jj1level/jj1event/jj1bridge.cpp src/jj1level/jj1event/jj1event.cpp \
	src/jj1level/jj1event/jj1guardians.cpp \
	src/jj1level/jj1event/jj1standardevent.cpp \
	src/jj1level/jj1levelplayer/jj1bird.cpp \
	src/jj1level/jj1levelplayer/jj1levelplayer.cpp \
	src/jj1level/jj1levelplayer/jj1levelplayerframe.cpp \
	src/jj1level/jj1bullet.cpp src/jj1level/jj1demolevel.cpp \
	src/jj1level/jj1level.cpp src/jj1level/jj1levelframe.cpp \
	src/jj1level/jj1levelload.cpp \
	src/jj1planet/jj1planet.cpp \
	src/jj1scene/jj1scene.cpp src/jj1scene/jj1sceneload.cpp \
	src/jj2level/jj2event/jj2event.cpp src/jj2level/jj2event/jj2eventframe.cpp \
	src/jj2level/jj2levelplayer/jj2levelplayer.cpp \
	src/jj2level/jj2levelplayer/jj2levelplayerframe.cpp \
	src/jj2level/jj2layer.cpp src/jj2level/jj2level.cpp \
	src/jj2level/jj2levelframe.cpp src/jj2level/jj2levelload.cpp \
	src/level/level.cpp src/level/movable.cpp src/level/levelplayer.cpp \
	src/menu/gamemenu.cpp src/menu/mainmenu.cpp src/menu/menu.cpp \
	src/menu/plasma.cpp src/menu/setupmenu.cpp \
	src/player/player.cpp \
	src/main.cpp src/setup.cpp src/util.cpp

openjazz_LDADD = -lz ${libSDL_LIBS} ${libmodplug_LIBS}
all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
src/game/$(am__dirstamp):
	@$(MKDIR_P) src/game
	@: > src/game/$(am__dirstamp)
src/game/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/game/$(DEPDIR)
	@: > src/game/$(DEPDIR)/$(am__dirstamp)
src/game/clientgame.$(OBJEXT): src/game/$(am__dirstamp) \
	src/game/$(DEPDIR)/$(am__dirstamp)
src/game/game.$(OBJEXT): src/game/$(am__dirstamp) \
	src/game/$(DEPDIR)/$(am__dirstamp)
src/game/gamemode.$(OBJEXT): src/game/$(am__dirstamp) \
	src/game/$(DEPDIR)/$(am__dirstamp)
src/game/localgame.$(OBJEXT): src/game/$(am__dirstamp) \
	src/game/$(DEPDIR)/$(am__dirstamp)
src/game/servergame.$(OBJEXT): src/game/$(am__dirstamp) \
	src/game/$(DEPDIR)/$(am__dirstamp)
src/io/gfx/$(am__dirstamp):
	@$(MKDIR_P) src/io/gfx
	@: > src/io/gfx/$(am__dirstamp)
src/io/gfx/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/io/gfx/$(DEPDIR)
	@: > src/io/gfx/$(DEPDIR)/$(am__dirstamp)
src/io/gfx/anim.$(OBJEXT): src/io/gfx/$(am__dirstamp) \
	src/io/gfx/$(DEPDIR)/$(am__dirstamp)
src/io/gfx/font.$(OBJEXT): src/io/gfx/$(am__dirstamp) \
	src/io/gfx/$(DEPDIR)/$(am__dirstamp)
src/io/gfx/paletteeffects.$(OBJEXT): src/io/gfx/$(am__dirstamp) \
	src/io/gfx/$(DEPDIR)/$(am__dirstamp)
src/io/gfx/sprite.$(OBJEXT): src/io/gfx/$(am__dirstamp) \
	src/io/gfx/$(DEPDIR)/$(am__dirstamp)
src/io/gfx/video.$(OBJEXT): src/io/gfx/$(am__dirstamp) \
	src/io/gfx/$(DEPDIR)/$(am__dirstamp)
src/io/gfx/scale2x/$(am__dirstamp):
	@$(MKDIR_P) src/io/gfx/scale2x
	@: > src/io/gfx/scale2x/$(am__dirstamp)
src/io/gfx/scale2x/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/io/gfx/scale2x/$(DEPDIR)
	@: > src/io/gfx/scale2x/$(DEPDIR)/$(am__dirstamp)
src/io/gfx/scale2x/getopt.$(OBJEXT):  \
	src/io/gfx/scale2x/$(am__dirstamp) \
	src/io/gfx/scale2x/$(DEPDIR)/$(am__dirstamp)
src/io/gfx/scale2x/pixel.$(OBJEXT):  \
	src/io/gfx/scale2x/$(am__dirstamp) \
	src/io/gfx/scale2x/$(DEPDIR)/$(am__dirstamp)
src/io/gfx/scale2x/scale2x.$(OBJEXT):  \
	src/io/gfx/scale2x/$(am__dirstamp) \
	src/io/gfx/scale2x/$(DEPDIR)/$(am__dirstamp)
src/io/gfx/scale2x/scale3x.$(OBJEXT):  \
	src/io/gfx/scale2x/$(am__dirstamp) \
	src/io/gfx/scale2x/$(DEPDIR)/$(am__dirstamp)
src/io/gfx/scale2x/scalebit.$(OBJEXT):  \
	src/io/gfx/scale2x/$(am__dirstamp) \
	src/io/gfx/scale2x/$(DEPDIR)/$(am__dirstamp)
src/io/gfx/scale2x/simple2x.$(OBJEXT):  \
	src/io/gfx/scale2x/$(am__dirstamp) \
	src/io/gfx/scale2x/$(DEPDIR)/$(am__dirstamp)
src/io/$(am__dirstamp):
	@$(MKDIR_P) src/io
	@: > src/io/$(am__dirstamp)
src/io/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/io/$(DEPDIR)
	@: > src/io/$(DEPDIR)/$(am__dirstamp)
src/io/controls.$(OBJEXT): src/io/$(am__dirstamp) \
	src/io/$(DEPDIR)/$(am__dirstamp)
src/io/file.$(OBJEXT): src/io/$(am__dirstamp) \
	src/io/$(DEPDIR)/$(am__dirstamp)
src/io/network.$(OBJEXT): src/io/$(am__dirstamp) \
	src/io/$(DEPDIR)/$(am__dirstamp)
src/io/sound.$(OBJEXT): src/io/$(am__dirstamp) \
	src/io/$(DEPDIR)/$(am__dirstamp)
src/jj1bonuslevel/jj1bonuslevelplayer/$(am__dirstamp):
	@$(MKDIR_P) src/jj1bonuslevel/jj1bonuslevelplayer
	@: > src/jj1bonuslevel/jj1bonuslevelplayer/$(am__dirstamp)
src/jj1bonuslevel/jj1bonuslevelplayer/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/jj1bonuslevel/jj1bonuslevelplayer/$(DEPDIR)
	@: > src/jj1bonuslevel/jj1bonuslevelplayer/$(DEPDIR)/$(am__dirstamp)
src/jj1bonuslevel/jj1bonuslevelplayer/jj1bonuslevelplayer.$(OBJEXT):  \
	src/jj1bonuslevel/jj1bonuslevelplayer/$(am__dirstamp) \
	src/jj1bonuslevel/jj1bonuslevelplayer/$(DEPDIR)/$(am__dirstamp)
src/jj1bonuslevel/$(am__dirstamp):
	@$(MKDIR_P) src/jj1bonuslevel
	@: > src/jj1bonuslevel/$(am__dirstamp)
src/jj1bonuslevel/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/jj1bonuslevel/$(DEPDIR)
	@: > src/jj1bonuslevel/$(DEPDIR)/$(am__dirstamp)
src/jj1bonuslevel/jj1bonuslevel.$(OBJEXT):  \
	src/jj1bonuslevel/$(am__dirstamp) \
	src/jj1bonuslevel/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1event/$(am__dirstamp):
	@$(MKDIR_P) src/jj1level/jj1event
	@: > src/jj1level/jj1event/$(am__dirstamp)
src/jj1level/jj1event/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/jj1level/jj1event/$(DEPDIR)
	@: > src/jj1level/jj1event/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1event/jj1bridge.$(OBJEXT):  \
	src/jj1level/jj1event/$(am__dirstamp) \
	src/jj1level/jj1event/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1event/jj1event.$(OBJEXT):  \
	src/jj1level/jj1event/$(am__dirstamp) \
	src/jj1level/jj1event/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1event/jj1guardians.$(OBJEXT):  \
	src/jj1level/jj1event/$(am__dirstamp) \
	src/jj1level/jj1event/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1event/jj1standardevent.$(OBJEXT):  \
	src/jj1level/jj1event/$(am__dirstamp) \
	src/jj1level/jj1event/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1levelplayer/$(am__dirstamp):
	@$(MKDIR_P) src/jj1level/jj1levelplayer
	@: > src/jj1level/jj1levelplayer/$(am__dirstamp)
src/jj1level/jj1levelplayer/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/jj1level/jj1levelplayer/$(DEPDIR)
	@: > src/jj1level/jj1levelplayer/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1levelplayer/jj1bird.$(OBJEXT):  \
	src/jj1level/jj1levelplayer/$(am__dirstamp) \
	src/jj1level/jj1levelplayer/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1levelplayer/jj1levelplayer.$(OBJEXT):  \
	src/jj1level/jj1levelplayer/$(am__dirstamp) \
	src/jj1level/jj1levelplayer/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1levelplayer/jj1levelplayerframe.$(OBJEXT):  \
	src/jj1level/jj1levelplayer/$(am__dirstamp) \
	src/jj1level/jj1levelplayer/$(DEPDIR)/$(am__dirstamp)
src/jj1level/$(am__dirstamp):
	@$(MKDIR_P) src/jj1level
	@: > src/jj1level/$(am__dirstamp)
src/jj1level/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/jj1level/$(DEPDIR)
	@: > src/jj1level/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1bullet.$(OBJEXT): src/jj1level/$(am__dirstamp) \
	src/jj1level/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1demolevel.$(OBJEXT): src/jj1level/$(am__dirstamp) \
	src/jj1level/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1level.$(OBJEXT): src/jj1level/$(am__dirstamp) \
	src/jj1level/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1levelframe.$(OBJEXT): src/jj1level/$(am__dirstamp) \
	src/jj1level/$(DEPDIR)/$(am__dirstamp)
src/jj1level/jj1levelload.$(OBJEXT): src/jj1level/$(am__dirstamp) \
	src/jj1level/$(DEPDIR)/$(am__dirstamp)
src/jj1planet/$(am__dirstamp):
	@$(MKDIR_P) src/jj1planet
	@: > src/jj1planet/$(am__dirstamp)
src/jj1planet/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/jj1planet/$(DEPDIR)
	@: > src/jj1planet/$(DEPDIR)/$(am__dirstamp)
src/jj1planet/jj1planet.$(OBJEXT): src/jj1planet/$(am__dirstamp) \
	src/jj1planet/$(DEPDIR)/$(am__dirstamp)
src/jj1scene/$(am__dirstamp):
	@$(MKDIR_P) src/jj1scene
	@: > src/jj1scene/$(am__dirstamp)
src/jj1scene/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/jj1scene/$(DEPDIR)
	@: > src/jj1scene/$(DEPDIR)/$(am__dirstamp)
src/jj1scene/jj1scene.$(OBJEXT): src/jj1scene/$(am__dirstamp) \
	src/jj1scene/$(DEPDIR)/$(am__dirstamp)
src/jj1scene/jj1sceneload.$(OBJEXT): src/jj1scene/$(am__dirstamp) \
	src/jj1scene/$(DEPDIR)/$(am__dirstamp)
src/jj2level/jj2event/$(am__dirstamp):
	@$(MKDIR_P) src/jj2level/jj2event
	@: > src/jj2level/jj2event/$(am__dirstamp)
src/jj2level/jj2event/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/jj2level/jj2event/$(DEPDIR)
	@: > src/jj2level/jj2event/$(DEPDIR)/$(am__dirstamp)
src/jj2level/jj2event/jj2event.$(OBJEXT):  \
	src/jj2level/jj2event/$(am__dirstamp) \
	src/jj2level/jj2event/$(DEPDIR)/$(am__dirstamp)
src/jj2level/jj2event/jj2eventframe.$(OBJEXT):  \
	src/jj2level/jj2event/$(am__dirstamp) \
	src/jj2level/jj2event/$(DEPDIR)/$(am__dirstamp)
src/jj2level/jj2levelplayer/$(am__dirstamp):
	@$(MKDIR_P) src/jj2level/jj2levelplayer
	@: > src/jj2level/jj2levelplayer/$(am__dirstamp)
src/jj2level/jj2levelplayer/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/jj2level/jj2levelplayer/$(DEPDIR)
	@: > src/jj2level/jj2levelplayer/$(DEPDIR)/$(am__dirstamp)
src/jj2level/jj2levelplayer/jj2levelplayer.$(OBJEXT):  \
	src/jj2level/jj2levelplayer/$(am__dirstamp) \
	src/jj2level/jj2levelplayer/$(DEPDIR)/$(am__dirstamp)
src/jj2level/jj2levelplayer/jj2levelplayerframe.$(OBJEXT):  \
	src/jj2level/jj2levelplayer/$(am__dirstamp) \
	src/jj2level/jj2levelplayer/$(DEPDIR)/$(am__dirstamp)
src/jj2level/$(am__dirstamp):
	@$(MKDIR_P) src/jj2level
	@: > src/jj2level/$(am__dirstamp)
src/jj2level/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/jj2level/$(DEPDIR)
	@: > src/jj2level/$(DEPDIR)/$(am__dirstamp)
src/jj2level/jj2layer.$(OBJEXT): src/jj2level/$(am__dirstamp) \
	src/jj2level/$(DEPDIR)/$(am__dirstamp)
src/jj2level/jj2level.$(OBJEXT): src/jj2level/$(am__dirstamp) \
	src/jj2level/$(DEPDIR)/$(am__dirstamp)
src/jj2level/jj2levelframe.$(OBJEXT): src/jj2level/$(am__dirstamp) \
	src/jj2level/$(DEPDIR)/$(am__dirstamp)
src/jj2level/jj2levelload.$(OBJEXT): src/jj2level/$(am__dirstamp) \
	src/jj2level/$(DEPDIR)/$(am__dirstamp)
src/level/$(am__dirstamp):
	@$(MKDIR_P) src/level
	@: > src/level/$(am__dirstamp)
src/level/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/level/$(DEPDIR)
	@: > src/level/$(DEPDIR)/$(am__dirstamp)
src/level/level.$(OBJEXT): src/level/$(am__dirstamp) \
	src/level/$(DEPDIR)/$(am__dirstamp)
src/level/movable.$(OBJEXT): src/level/$(am__dirstamp) \
	src/level/$(DEPDIR)/$(am__dirstamp)
src/level/levelplayer.$(OBJEXT): src/level/$(am__dirstamp) \
	src/level/$(DEPDIR)/$(am__dirstamp)
src/menu/$(am__dirstamp):
	@$(MKDIR_P) src/menu
	@: > src/menu/$(am__dirstamp)
src/menu/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/menu/$(DEPDIR)
	@: > src/menu/$(DEPDIR)/$(am__dirstamp)
src/menu/gamemenu.$(OBJEXT): src/menu/$(am__dirstamp) \
	src/menu/$(DEPDIR)/$(am__dirstamp)
src/menu/mainmenu.$(OBJEXT): src/menu/$(am__dirstamp) \
	src/menu/$(DEPDIR)/$(am__dirstamp)
src/menu/menu.$(OBJEXT): src/menu/$(am__dirstamp) \
	src/menu/$(DEPDIR)/$(am__dirstamp)
src/menu/plasma.$(OBJEXT): src/menu/$(am__dirstamp) \
	src/menu/$(DEPDIR)/$(am__dirstamp)
src/menu/setupmenu.$(OBJEXT): src/menu/$(am__dirstamp) \
	src/menu/$(DEPDIR)/$(am__dirstamp)
src/player/$(am__dirstamp):
	@$(MKDIR_P) src/player
	@: > src/player/$(am__dirstamp)
src/player/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/player/$(DEPDIR)
	@: > src/player/$(DEPDIR)/$(am__dirstamp)
src/player/player.$(OBJEXT): src/player/$(am__dirstamp) \
	src/player/$(DEPDIR)/$(am__dirstamp)
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/main.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/setup.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/util.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)

openjazz$(EXEEXT): $(openjazz_OBJECTS) $(openjazz_DEPENDENCIES) $(EXTRA_openjazz_DEPENDENCIES) 
	@rm -f openjazz$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(openjazz_OBJECTS) $(openjazz_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/*.$(OBJEXT)
	-rm -f src/game/*.$(OBJEXT)
	-rm -f src/io/*.$(OBJEXT)
	-rm -f src/io/gfx/*.$(OBJEXT)
	-rm -f src/io/gfx/scale2x/*.$(OBJEXT)
	-rm -f src/jj1bonuslevel/*.$(OBJEXT)
	-rm -f src/jj1bonuslevel/jj1bonuslevelplayer/*.$(OBJEXT)
	-rm -f src/jj1level/*.$(OBJEXT)
	-rm -f src/jj1level/jj1event/*.$(OBJEXT)
	-rm -f src/jj1level/jj1levelplayer/*.$(OBJEXT)
	-rm -f src/jj1planet/*.$(OBJEXT)
	-rm -f src/jj1scene/*.$(OBJEXT)
	-rm -f src/jj2level/*.$(OBJEXT)
	-rm -f src/jj2level/jj2event/*.$(OBJEXT)
	-rm -f src/jj2level/jj2levelplayer/*.$(OBJEXT)
	-rm -f src/level/*.$(OBJEXT)
	-rm -f src/menu/*.$(OBJEXT)
	-rm -f src/player/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/main.Po
include src/$(DEPDIR)/setup.Po
include src/$(DEPDIR)/util.Po
include src/game/$(DEPDIR)/clientgame.Po
include src/game/$(DEPDIR)/game.Po
include src/game/$(DEPDIR)/gamemode.Po
include src/game/$(DEPDIR)/localgame.Po
include src/game/$(DEPDIR)/servergame.Po
include src/io/$(DEPDIR)/controls.Po
include src/io/$(DEPDIR)/file.Po
include src/io/$(DEPDIR)/network.Po
include src/io/$(DEPDIR)/sound.Po
include src/io/gfx/$(DEPDIR)/anim.Po
include src/io/gfx/$(DEPDIR)/font.Po
include src/io/gfx/$(DEPDIR)/paletteeffects.Po
include src/io/gfx/$(DEPDIR)/sprite.Po
include src/io/gfx/$(DEPDIR)/video.Po
include src/io/gfx/scale2x/$(DEPDIR)/getopt.Po
include src/io/gfx/scale2x/$(DEPDIR)/pixel.Po
include src/io/gfx/scale2x/$(DEPDIR)/scale2x.Po
include src/io/gfx/scale2x/$(DEPDIR)/scale3x.Po
include src/io/gfx/scale2x/$(DEPDIR)/scalebit.Po
include src/io/gfx/scale2x/$(DEPDIR)/simple2x.Po
include src/jj1bonuslevel/$(DEPDIR)/jj1bonuslevel.Po
include src/jj1bonuslevel/jj1bonuslevelplayer/$(DEPDIR)/jj1bonuslevelplayer.Po
include src/jj1level/$(DEPDIR)/jj1bullet.Po
include src/jj1level/$(DEPDIR)/jj1demolevel.Po
include src/jj1level/$(DEPDIR)/jj1level.Po
include src/jj1level/$(DEPDIR)/jj1levelframe.Po
include src/jj1level/$(DEPDIR)/jj1levelload.Po
include src/jj1level/jj1event/$(DEPDIR)/jj1bridge.Po
include src/jj1level/jj1event/$(DEPDIR)/jj1event.Po
include src/jj1level/jj1event/$(DEPDIR)/jj1guardians.Po
include src/jj1level/jj1event/$(DEPDIR)/jj1standardevent.Po
include src/jj1level/jj1levelplayer/$(DEPDIR)/jj1bird.Po
include src/jj1level/jj1levelplayer/$(DEPDIR)/jj1levelplayer.Po
include src/jj1level/jj1levelplayer/$(DEPDIR)/jj1levelplayerframe.Po
include src/jj1planet/$(DEPDIR)/jj1planet.Po
include src/jj1scene/$(DEPDIR)/jj1scene.Po
include src/jj1scene/$(DEPDIR)/jj1sceneload.Po
include src/jj2level/$(DEPDIR)/jj2layer.Po
include src/jj2level/$(DEPDIR)/jj2level.Po
include src/jj2level/$(DEPDIR)/jj2levelframe.Po
include src/jj2level/$(DEPDIR)/jj2levelload.Po
include src/jj2level/jj2event/$(DEPDIR)/jj2event.Po
include src/jj2level/jj2event/$(DEPDIR)/jj2eventframe.Po
include src/jj2level/jj2levelplayer/$(DEPDIR)/jj2levelplayer.Po
include src/jj2level/jj2levelplayer/$(DEPDIR)/jj2levelplayerframe.Po
include src/level/$(DEPDIR)/level.Po
include src/level/$(DEPDIR)/levelplayer.Po
include src/level/$(DEPDIR)/movable.Po
include src/menu/$(DEPDIR)/gamemenu.Po
include src/menu/$(DEPDIR)/mainmenu.Po
include src/menu/$(DEPDIR)/menu.Po
include src/menu/$(DEPDIR)/plasma.Po
include src/menu/$(DEPDIR)/setupmenu.Po
include src/player/$(DEPDIR)/player.Po

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`
install-pkgdataDATA: $(pkgdata_DATA)
	@$(NORMAL_INSTALL)
	@list='$(pkgdata_DATA)'; test -n "$(pkgdatadir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgdatadir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(pkgdatadir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgdatadir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgdatadir)" || exit $$?; \
	done
	install -m 0644 data/* /usr/share/openjazz

uninstall-pkgdataDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgdata_DATA)'; test -n "$(pkgdatadir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgdatadir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)
dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(DATA)
installdirs:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(pkgdatadir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f src/game/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/game/$(am__dirstamp)
	-rm -f src/io/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/io/$(am__dirstamp)
	-rm -f src/io/gfx/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/io/gfx/$(am__dirstamp)
	-rm -f src/io/gfx/scale2x/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/io/gfx/scale2x/$(am__dirstamp)
	-rm -f src/jj1bonuslevel/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/jj1bonuslevel/$(am__dirstamp)
	-rm -f src/jj1bonuslevel/jj1bonuslevelplayer/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/jj1bonuslevel/jj1bonuslevelplayer/$(am__dirstamp)
	-rm -f src/jj1level/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/jj1level/$(am__dirstamp)
	-rm -f src/jj1level/jj1event/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/jj1level/jj1event/$(am__dirstamp)
	-rm -f src/jj1level/jj1levelplayer/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/jj1level/jj1levelplayer/$(am__dirstamp)
	-rm -f src/jj1planet/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/jj1planet/$(am__dirstamp)
	-rm -f src/jj1scene/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/jj1scene/$(am__dirstamp)
	-rm -f src/jj2level/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/jj2level/$(am__dirstamp)
	-rm -f src/jj2level/jj2event/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/jj2level/jj2event/$(am__dirstamp)
	-rm -f src/jj2level/jj2levelplayer/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/jj2level/jj2levelplayer/$(am__dirstamp)
	-rm -f src/level/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/level/$(am__dirstamp)
	-rm -f src/menu/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/menu/$(am__dirstamp)
	-rm -f src/player/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/player/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR) src/game/$(DEPDIR) src/io/$(DEPDIR) src/io/gfx/$(DEPDIR) src/io/gfx/scale2x/$(DEPDIR) src/jj1bonuslevel/$(DEPDIR) src/jj1bonuslevel/jj1bonuslevelplayer/$(DEPDIR) src/jj1level/$(DEPDIR) src/jj1level/jj1event/$(DEPDIR) src/jj1level/jj1levelplayer/$(DEPDIR) src/jj1planet/$(DEPDIR) src/jj1scene/$(DEPDIR) src/jj2level/$(DEPDIR) src/jj2level/jj2event/$(DEPDIR) src/jj2level/jj2levelplayer/$(DEPDIR) src/level/$(DEPDIR) src/menu/$(DEPDIR) src/player/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-pkgdataDATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR) src/game/$(DEPDIR) src/io/$(DEPDIR) src/io/gfx/$(DEPDIR) src/io/gfx/scale2x/$(DEPDIR) src/jj1bonuslevel/$(DEPDIR) src/jj1bonuslevel/jj1bonuslevelplayer/$(DEPDIR) src/jj1level/$(DEPDIR) src/jj1level/jj1event/$(DEPDIR) src/jj1level/jj1levelplayer/$(DEPDIR) src/jj1planet/$(DEPDIR) src/jj1scene/$(DEPDIR) src/jj2level/$(DEPDIR) src/jj2level/jj2event/$(DEPDIR) src/jj2level/jj2levelplayer/$(DEPDIR) src/level/$(DEPDIR) src/menu/$(DEPDIR) src/player/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-pkgdataDATA

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic cscope \
	cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-pkgdataDATA install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic pdf pdf-am \
	ps ps-am tags tags-am uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-pkgdataDATA

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
